apiVersion: v1
kind: ConfigMap
metadata:
  name: gptscript-agent-config
data:
  GPTSCRIPT_DEFAULT_MODEL: "gpt-4o"
  OPENAI_BASE_URL: "https://api.openai.com/v1"
  AGENT_FILE: "simple-k8s-fix.gpt"
  COMMAND_STRING: "Does my cluster has any issues?"
  OUTSIDE_AGENTS_FILES: "https://raw.githubusercontent.com/victorgetz/gptscript-agents/main/gptscript-bot/files/devops-bot.gpt, https://github.com/victorgetz/gptscript-agents/blob/main/gptscript-bot/files/shared-context.gpt"
  #GPTSCRIPT_CACHE_DIR: "/home/agentuser/.cache/gptscript"
  #GPTSCRIPT_CONFIG: "/home/agentuser/.config/gptscript/config.yaml"
  #GPTSCRIPT_WORKSPACE: "/home/agentuser/workspace"