apiVersion: v1
kind: ConfigMap
metadata:
  name: gptscript-agent-config
data:
  GPTSCRIPT_DEFAULT_MODEL: "gpt-4o"
  OPENAI_BASE_URL: "https://api.openai.com/v1"
  MERGED_AGENT_FILE: "simple-cli-agent.gpt"
  COMMAND_STRING: "Does my cluster has any issues?"