apiVersion: v1
kind: Pod
metadata:
  name: crash-loop-pod
  namespace: default
spec:
  containers:
  - name: crash-loop-container
    image: busybox
    command: ["sh", "-c", "exit 1"] # Dieses Kommando führt zu einem sofortigen Fehler und verursacht CrashLoopBackOff